const data = [
    {
        "name": "Val Thorens (Les 3 Vallées)",
        "country": "France",
        "totalSlopeKm": 150,
        "greenSlopeKm": 15,
        "blueSlopeKm": 55,
        "redSlopeKm": 60,
        "blackSlopeKm": 20,
        "altitude": "2,300m",
        "closestAirport": "Chambery",
        "distanceFromAirportKm": 122,
        "transferOptions": ["private transfer", "shared bus", "train to Moutiers + bus"],
        "skiPassPrice6Days": 320,
        "averageHotelPrice6Days": 3200,
        "description": "Val Thorens is renowned for its excellent snow conditions in December, thanks to its high altitude. It typically has one of the longest ski seasons in the Alps.",
        "image": "https://mediaim.expedia.com/destination/1/e087e628c2a78b6438b4349f25ccb3f9.jpg",
        "flag": "https://flagcdn.com/w20/fr.png"
    },
    {
        "name": "Tignes/Val d'Isère (Espace Killy)",
        "country": "France",
        "totalSlopeKm": 300,
        "greenSlopeKm": 22,
        "blueSlopeKm": 148,
        "redSlopeKm": 106,
        "blackSlopeKm": 24,
        "altitude": "Tignes (2,100m), Val d'Isère (1,850m)",
        "closestAirport": "Geneva",
        "distanceFromAirportKm": 220,
        "transferOptions": ["private transfer", "shared bus", "train to Bourg St Maurice + bus"],
        "skiPassPrice6Days": 330,
        "averageHotelPrice6Days": 2800,
        "description": "Espace Killy is known for its reliable early-season snow, with both resorts offering high-altitude slopes and glacier skiing. Tignes in particular has a glacier that often allows skiing as early as October.",
        "image": "https://apioairuxm.cloudimg.io/width/1200/foil1/https://www.skiworld.co.uk/images/uploads/photos/large/espace_killy_ski_area_-_val_disere_-_%C2%A9andyparant.com_12668.jpg",
        "flag": "https://flagcdn.com/w20/fr.png"
    },
    {
        "name": "Sölden",
        "country": "Austria",
        "totalSlopeKm": 144,
        "greenSlopeKm": 9,
        "blueSlopeKm": 62,
        "redSlopeKm": 45,
        "blackSlopeKm": 28,
        "altitude": "1,377m to 3,340m",
        "closestAirport": "Innsbruck",
        "distanceFromAirportKm": 85,
        "transferOptions": ["private transfer", "shared bus", "train to Ötztal Bahnhof + bus"],
        "skiPassPrice6Days": 322,
        "averageHotelPrice6Days": 2500,
        "description": "Sölden is a great choice for December skiing, with two glaciers (Rettenbach and Tiefenbach) ensuring good snow conditions. It’s known for its early start to the season and reliable snow.",
        "image": "https://content.igluski.com/images/_i60355318.jpg",
        "flag": "https://flagcdn.com/w20/at.png"
    },
    {
        "name": "Zermatt-Cervinia",
        "country": "Switzerland/Italy",
        "totalSlopeKm": 360,
        "greenSlopeKm": 22,
        "blueSlopeKm": 86,
        "redSlopeKm": 202,
        "blackSlopeKm": 50,
        "altitude": "Zermatt (1,620m), Cervinia (2,050m)",
        "closestAirport": "Geneva",
        "distanceFromAirportKm": 231,
        "transferOptions": ["private transfer", "train to Visp + train to Zermatt"],
        "skiPassPrice6Days": 360,
        "averageHotelPrice6Days": 3600,
        "description": "The Zermatt-Cervinia area offers excellent December skiing, with high-altitude slopes and glacier skiing on the Matterhorn Glacier Paradise, ensuring good snow conditions.",
        "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuJvSTZPp01PaZ93K8ZYo1t7qSgxnakzwfQw&s",
        "flag": ["https://flagcdn.com/w20/ch.png", "https://flagcdn.com/w20/it.png"]
    },
    {
        "name": "Obergurgl-Hochgurgl",
        "country": "Austria",
        "totalSlopeKm": 112,
        "greenSlopeKm": 6,
        "blueSlopeKm": 29,
        "redSlopeKm": 61,
        "blackSlopeKm": 16,
        "altitude": "1,800m to 3,080m",
        "closestAirport": "Innsbruck",
        "distanceFromAirportKm": 96,
        "transferOptions": ["private transfer", "shared bus", "train to Ötztal Bahnhof + bus"],
        "skiPassPrice6Days": 305,
        "averageHotelPrice6Days": 2200,
        "description": "Obergurgl-Hochgurgl is one of Austria’s highest resorts, known for its early-season reliability. The resort typically opens in mid-November and offers a long season with good snow quality.",
        "image": "https://diamant-der-alpen.obergurgl.com/wp-content/uploads/2018/01/obergurgl-hochgurgl-rechteck-ortsbild-winter-beitragsbild-1200x675.jpg",
        "flag": "https://flagcdn.com/w20/at.png"
    },
    {
        "name": "Ischgl (Silvretta Arena)",
        "country": "Austria",
        "totalSlopeKm": 239,
        "greenSlopeKm": 15,
        "blueSlopeKm": 92,
        "redSlopeKm": 94,
        "blackSlopeKm": 38,
        "altitude": "1,377m to 2,872m",
        "closestAirport": "Innsbruck",
        "distanceFromAirportKm": 100,
        "transferOptions": ["private transfer", "shared bus", "train to Landeck-Zams + bus"],
        "skiPassPrice6Days": 312,
        "averageHotelPrice6Days": 3000,
        "description": "Ischgl, in the Silvretta Arena, is famous for its early and long ski season. The resort’s high-altitude slopes and extensive snowmaking make it a safe bet for December skiing.",
        "image": "https://www.worldsnowboardguide.com/asset/E67936AE-E38B-4601-9F2F882E60DADC84/1200x800-highQuality/",
        "flag": "https://flagcdn.com/w20/at.png"
    },
    {
        "name": "Les Deux Alpes",
        "country": "France",
        "totalSlopeKm": 200,
        "greenSlopeKm": 15,
        "blueSlopeKm": 81,
        "redSlopeKm": 88,
        "blackSlopeKm": 16,
        "altitude": "1,300m to 3,600m",
        "closestAirport": "Grenoble",
        "distanceFromAirportKm": 113,
        "transferOptions": ["private transfer", "shared bus", "train to Grenoble + bus"],
        "skiPassPrice6Days": 295,
        "averageHotelPrice6Days": 2400,
        "description": "Les Deux Alpes offers glacier skiing, which ensures good snow conditions in December. The resort’s high-altitude terrain provides reliable early-season skiing.",
        "image": "https://restlessfeet.com/wp-content/uploads/2020/09/Glacier-from-Jandri-2.jpg",
        "flag": "https://flagcdn.com/w20/fr.png"
    },
    {
        "name": "Courchevel (Les 3 Vallées)",
        "country": "France",
        "totalSlopeKm": 150,
        "greenSlopeKm": 20,
        "blueSlopeKm": 52,
        "redSlopeKm": 68,
        "blackSlopeKm": 10,
        "altitude": "1,850m",
        "closestAirport": "Chambery",
        "distanceFromAirportKm": 120,
        "transferOptions": ["private transfer", "shared bus", "train to Moutiers + bus"],
        "skiPassPrice6Days": 330,
        "averageHotelPrice6Days": 3200,
        "description": "Courchevel benefits from high-altitude slopes and extensive snowmaking capabilities, making it one of the more reliable options for early-season skiing in the 3 Vallées area.",
        "image": "https://www.powderhounds.com/site/DefaultSite/filesystem/images/Europe/France/Courchevel/overview/01.JPG",
        "flag": "https://flagcdn.com/w20/fr.png"
    },
    {
        "name": "La Plagne (Paradiski)",
        "country": "France",
        "totalSlopeKm": 225,
        "greenSlopeKm": 15,
        "blueSlopeKm": 137,
        "redSlopeKm": 55,
        "blackSlopeKm": 18,
        "altitude": "1,250m to 3,250m",
        "closestAirport": "Chambery",
        "distanceFromAirportKm": 120,
        "transferOptions": ["private transfer", "shared bus", "train to Aime-La-Plagne + bus"],
        "skiPassPrice6Days": 310,
        "averageHotelPrice6Days": 2700,
        "description": "La Plagne, part of Paradiski, has high-altitude slopes and glacier skiing, offering good snow reliability in December. It’s a great option for families and intermediates looking for early-season skiing.",
        "image": "https://cf.bstatic.com/xdata/images/hotel/max1024x768/336746002.jpg?k=585623961b3e1453f8f3e233b508e52415a4ca792daebf5c6382091f083c988b&o=&hp=1",
        "flag": "https://flagcdn.com/w20/fr.png"
    },
    {
        "name": "Saalbach Hinterglemm Leogang Fieberbrunn (Skicircus)",
        "country": "Austria",
        "totalSlopeKm": 270,
        "greenSlopeKm": 15,
        "blueSlopeKm": 125,
        "redSlopeKm": 120,
        "blackSlopeKm": 10,
        "altitude": "840m to 2,096m",
        "closestAirport": "Salzburg",
        "distanceFromAirportKm": 86,
        "transferOptions": ["private transfer", "shared bus", "train to Zell am See + bus"],
        "skiPassPrice6Days": 310,
        "averageHotelPrice6Days": 2600,
        "description": "The Skicircus area offers a large network of blue slopes, making it very suitable for beginners and intermediates. Its robust snowmaking ensures good conditions in December.",
        "image": "https://cdn.indebergen.nl/media/nfqjqyg1/atsalz10-skicircus-saalbach-hinterglemm-leogang.jpg?anchor=center&mode=crop&width=1080&height=608&format=webp&quality=80",
        "flag": "https://flagcdn.com/w20/at.png"
    }
];

export { data };